name: Docker Image Test Suite

on:
  push:
    branches: [*]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the image and run the tests
      run: docker build --file tests/Dockerfile .
